# CUSTOMER SEGMENTATION

##**1.Import Libraries**

In [13]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import silhouette_score

## **2.Loading Dataset**

In [14]:
df = pd.read_csv('ML_Ready_Dataset.csv')
df

       Gender       Age  Annual Income (k$)  Spending Score (1-100)
0    1.128152 -1.424569           -1.738999               -0.434801
1    1.128152 -1.281035           -1.738999                1.195704
2   -0.886405 -1.352802           -1.700830               -1.715913
3   -0.886405 -1.137502           -1.700830                1.040418
4   -0.886405 -0.563369           -1.662660               -0.395980
..        ...       ...                 ...                     ...
195 -0.886405 -0.276302            2.268791                1.118061
196 -0.886405  0.441365            2.497807               -0.861839
197  1.128152 -0.491602            2.497807                0.923953
198  1.128152 -0.491602            2.917671               -1.250054
199  1.128152 -0.635135            2.917671                1.273347

[200 rows x 4 columns]

## **3.K-Means Clustering**

In [15]:
kmeans = KMeans(
    n_clusters=5,
    random_state=42,
    n_init=10
)

df['Cluster'] = kmeans.fit_predict(df)

df.head()

     Gender       Age  Annual Income (k$)  Spending Score (1-100)  Cluster
0  1.128152 -1.424569           -1.738999               -0.434801        3
1  1.128152 -1.281035           -1.738999                1.195704        3
2 -0.886405 -1.352802           -1.700830               -1.715913        3
3 -0.886405 -1.137502           -1.700830                1.040418        3
4 -0.886405 -0.563369           -1.662660               -0.395980        3

## **4. Split Features and Target**

In [16]:
X = df.drop("Cluster", axis=1)
y = df["Cluster"]

## **5.Train-Test Split**

In [17]:
kmeans = KMeans(
    n_clusters=5,
    random_state=42,
    n_init=10
)

clusters = kmeans.fit_predict(X)

## **6. Add Cluster Labels**

In [18]:
X['Cluster'] = clusters

X.head()

     Gender       Age  Annual Income (k$)  Spending Score (1-100)  Cluster
0  1.128152 -1.424569           -1.738999               -0.434801        3
1  1.128152 -1.281035           -1.738999                1.195704        3
2 -0.886405 -1.352802           -1.700830               -1.715913        3
3 -0.886405 -1.137502           -1.700830                1.040418        3
4 -0.886405 -0.563369           -1.662660               -0.395980        3

## **7. PCA Visualization**

In [19]:
pca = PCA(n_components=2)

X_pca = pca.fit_transform(
    X.drop('Cluster', axis=1)
)

In [20]:
pca_df = pd.DataFrame(
    X_pca,
    columns=['PC1','PC2']
)

pca_df['Cluster'] = clusters

## **8. Silhouette Score**

In [21]:
score = silhouette_score(
    X.drop('Cluster', axis=1),
    clusters
)

print("Silhouette Score:", round(score,3))

Silhouette Score: 0.304

## **9. Cluster Summary**

In [22]:
cluster_summary = X.groupby('Cluster').mean()

cluster_summary

           Gender       Age  Annual Income (k$)  Spending Score (1-100)
Cluster
0        0.043390 -0.441917            0.991583                1.239503
1        0.016672 -0.169889            1.105281               -1.250054
2       -0.886405  0.786847           -0.432362               -0.393271
3       -0.065660 -1.000614           -0.795366                0.427181
4        1.128152  1.210294           -0.262388               -0.521318

## **10. Business Interpretation**

After viewing the cluster averages:



---


* **Cluster 0**

High Income

Low Spending

Strategy: Give personalized offers and loyalty rewards.

---


* **Cluster 1**

High Income

High Spending


Strategy: VIP membership and premium products.

---

* **Cluster 2**

Low Income

High Spending

Strategy: Discount bundles and promotional campaigns.

---

* **Cluster 3**

Low Income

Low Spending

Strategy: Awareness campaigns and affordable products.

---

* **Cluster 4**

Medium Income

Medium Spending

Strategy: Cross-selling and seasonal offers.

---

## **Save Final Dataset**

In [23]:
X.to_csv(
    "Customer_Segments.csv",
    index=False
)

print("Customer segmentation completed!")

Customer segmentation completed!

In [25]:
from google.colab import drive
drive.mount('/content/drive')

X.to_csv('/content/drive/MyDrive/Customer_Segments.csv', index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).