**Customer Tier Generation & AI Recommendation System**

---

**The objective of this notebook is to:

Convert numerical clusters into business-friendly customer segments.

Analyze each customer segment.

Generate personalized marketing recommendations.

Prepare the final dataset for the Streamlit dashboard.**

---

In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("Customer_Segments.csv")

In [5]:
df["Cluster"].value_counts().sort_index()

Cluster
0    39
1    29
2    43
3    54
4    35
Name: count, dtype: int64

In [7]:
df.head()

     Gender       Age  Annual Income (k$)  Spending Score (1-100)  Cluster
0  1.128152 -1.424569           -1.738999               -0.434801        3
1  1.128152 -1.281035           -1.738999                1.195704        3
2 -0.886405 -1.352802           -1.700830               -1.715913        3
3 -0.886405 -1.137502           -1.700830                1.040418        3
4 -0.886405 -0.563369           -1.662660               -0.395980        3

**Cluster Distribution**

---

In [8]:
cluster_count = df["Cluster"].value_counts().sort_index()

print(cluster_count)

Cluster
0    39
1    29
2    43
3    54
4    35
Name: count, dtype: int64

In [9]:
cluster_summary = (
    df.groupby("Cluster")
      .mean()
      .round(2)
)

cluster_summary

         Gender   Age  Annual Income (k$)  Spending Score (1-100)
Cluster
0          0.04 -0.44                0.99                    1.24
1          0.02 -0.17                1.11                   -1.25
2         -0.89  0.79               -0.43                   -0.39
3         -0.07 -1.00               -0.80                    0.43
4          1.13  1.21               -0.26                   -0.52

**Assign Business-Friendly Segment Names**

From your cluster statistics, the clusters can reasonably be interpreted as:

Cluster	Interpretation	Segment
0	High Income + High Spending -	VIP Customers

1	High Income + Low Spending	- Potential Customers

2	Medium Income + Medium Spending	- Regular Customers

3	Young + Good Spending	- Young Shoppers

4	Low Income + Low Spending	- Budget Customers

In [10]:
segment_map = {
    0: "VIP Customers",
    1: "Potential Customers",
    2: "Regular Customers",
    3: "Young Shoppers",
    4: "Budget Customers"
}

df["Segment"] = df["Cluster"].map(segment_map)

In [11]:
recommendation_map = {

    "VIP Customers":
    "Offer premium membership, exclusive rewards and early access to new collections.",

    "Potential Customers":
    "Provide personalized product recommendations and loyalty offers to increase spending.",

    "Regular Customers":
    "Encourage repeat purchases through reward points and bundle discounts.",

    "Young Shoppers":
    "Promote trending products, seasonal collections and student offers.",

    "Budget Customers":
    "Provide discount coupons, cashback offers and festival sales."
}

df["Recommendation"] = df["Segment"].map(recommendation_map)

In [12]:
df.head()

,Gender,Age,Annual Income (k$),Spending Score (1-100),Cluster,Segment,Recommendation
0,1.128152,-1.424569,-1.738999,-0.434801,3,Young Shoppers,"Promote trending products, seasonal collection..."
1,1.128152,-1.281035,-1.738999,1.195704,3,Young Shoppers,"Promote trending products, seasonal collection..."
2,-0.886405,-1.352802,-1.700830,-1.715913,3,Young Shoppers,"Promote trending products, seasonal collection..."
3,-0.886405,-1.137502,-1.700830,1.040418,3,Young Shoppers,"Promote trending products, seasonal collection..."
4,-0.886405,-0.563369,-1.662660,-0.395980,3,Young Shoppers,"Promote trending products, seasonal collection..."

In [13]:
segment_summary = (
    df.groupby("Segment")
      .agg(
          Customers=("Cluster","count"),
          Average_Age=("Age","mean"),
          Average_Income=("Annual Income (k$)","mean"),
          Average_Spending=("Spending Score (1-100)","mean")
      )
      .round(2)
)

segment_summary

                     Customers  Average_Age  Average_Income  Average_Spending
Segment
Budget Customers            35         1.21           -0.26             -0.52
Potential Customers         29        -0.17            1.11             -1.25
Regular Customers           43         0.79           -0.43             -0.39
VIP Customers               39        -0.44            0.99              1.24
Young Shoppers              54        -1.00           -0.80              0.43

**10. Business Insights (Markdown)**

**Observation 1**

VIP Customers have relatively higher income and spending behaviour. They should receive premium services to improve customer retention.

**Observation 2**

Potential Customers have high purchasing power but lower spending. Personalized marketing campaigns can encourage higher purchases.

**Observation 3**

Young Shoppers show good spending behaviour despite relatively lower income. Trend-based marketing is likely to be effective.

**Observation 4**

Budget Customers spend less and have lower income. Discounts and cashback offers can help increase their engagement.

**Observation 5**

Regular Customers form a stable customer base and should be retained through loyalty programs.

---

In [14]:
df.to_csv("Final_Customers.csv", index=False)

print("Final dataset created successfully.")

Final dataset created successfully.